### ISSUE TITLE
initLiveReact() causes Object(...) is not a function error with Webpack

### ISSUE THREAD

**Issue by tmepple** [fidr/phoenix_live_react#1]
Thanks for the great library!

Using phoenix_live_view master, Phoenix 1.4.10, Elixir 1.9.2, MacOS 10.14.6, Webpack 4.41.2, Chrome 77.0.3865.120

I followed the instructions adding the optional `initLiveReact()` function to my app.js:

```js
import MyComponent from "./my_component";
window.Components = {
  MyComponent
};

import LiveReact, { initLiveReact } from "phoenix_live_react";
import { Socket } from "phoenix";
import LiveSocket from "phoenix_live_view";

let hooks = { LiveReact };
let liveSocket = new LiveSocket("/live", Socket, { hooks });
liveSocket.connect();

document.addEventListener("DOMContentLoaded", e => {
  initLiveReact();
});
```
When initLiveReact() is called I am getting this error:
<img width="444" alt="Screen Shot 2019-10-16 at 7 08 24 PM" src="https://user-images.githubusercontent.com/1711033/66965677-8a4b1a00-f048-11e9-9f8d-d84542b62849.png">

Then after the LV socket connects everything works great but the React component is not rendered immediately after the page loads due to the error.

Looking at the compiled Webpack code for some reason it's wrapping in an Object(...) which seems to be causing the error message:
<img width="532" alt="Screen Shot 2019-10-16 at 7 13 35 PM" src="https://user-images.githubusercontent.com/1711033/66965822-14937e00-f049-11e9-9c8b-8fe5dac9ebd5.png">

**Comment by fidr** [comment]
Good catch! I noticed I didn't update the readme with the latest version. 

The (somewhat cryptic) error is happening because `initLiveReact` does not exist in the old version. Can you try with the latest version?


```elixir
{:phoenix_live_react, "~> 0.2.0"}
```

**Comment by tmepple** [comment]
Thanks @fidr for the fast response.  Bumping the version worked!  Sorry I should have checked versions on hex.pm first but the error message was cryptic and had me troubleshooting in a completely different direction.
