### ISSUE TITLE
Warning when used?

### ISSUE THREAD

**Issue by shizhaojingszj** [fidr/phoenix_live_react#28]
> react-dom.development.js:86 Warning: React does not recognize the `pushEvent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pushevent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Is there any way to remove them?

**Comment by fidr** [comment]
Looking at the warning, it seems that you pass `pushEvent` to an actual html element in the DOM. Perhaps something like `<div {...props}></div>`?
