### ISSUE TITLE
Warnings when attempting to use React 18

### ISSUE THREAD

**Issue by apreifsteck** [fidr/phoenix_live_react#31]
Hello!

I was recently attempting to get started with this library, and following the instructions, got this warning:
![image](https://github.com/fidr/phoenix_live_react/assets/17051367/ec57286c-ab2a-43d3-823a-fe75075c9865)

Here is the component I was trying to use, in it's entirety:
```TypeScript
import React from "react"
export default function Hello() {
  return (
    <>
      <h1>Hello from React</h1>
    </>
  )
}
```

package.json dependencies:
```json
  "dependencies": {
    "jest-environment-jsdom": "^29.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
```

**Comment by adamwdennis** [comment]
Is there a way around this?

**Comment by apreifsteck** [comment]
We ended up downgrading to React 17, if I recall correctly.

**Comment by adamwdennis** [comment]
This is now fixed with https://github.com/fidr/phoenix_live_react/pull/34
